### ISSUE TITLE
The widget doesn work

### ISSUE THREAD

**Issue by AndresSanRo** [jaebirds/Alpha-Rotating-Feed-w-Goal#1]
I have followed the instrunctions in the README file and it doesn´t work.

The console gives an error when I publish the widget with the actual code: Uncaught (in promise) TypeError: Cannot read property 'amount' of undefined
![image](https://user-images.githubusercontent.com/39009262/111374782-c8b19200-869d-11eb-8086-a6a66bdd0313.png)

Also, debugging I think the error is near this piece of code.
![image](https://user-images.githubusercontent.com/39009262/111375076-234aee00-869e-11eb-941a-324279f31032.png)

A fix would be appreciated.
Cheers

**Comment by jaebirds** [comment]
Hi, can you confirm for me that the options updated properly? They should look something like this:

![Screenshot 2021-03-16 170959](https://user-images.githubusercontent.com/25286658/111380249-7743db80-867a-11eb-8d62-10fafd4003a3.png)

**Comment by AndresSanRo** [comment]
Yes, It appears that they have updated properly, here is a screenshot of my properties panel, It looks similar to yours
![image](https://user-images.githubusercontent.com/39009262/111388420-83965b80-86af-11eb-9a71-543aa91db4fd.png)

**Comment by jaebirds** [comment]
I actually noticed in your first post that the code is a bit different than what it should be. Can you try copying and pasting all the code again and see if that works? If you're still getting the same error, what settings do you have set under Goal?

**Comment by AndresSanRo** [comment]
The goal setting had by default the value "none" and that was causing the js error. after changing it to other value the widget worked again, still, I think it would be better if this field could have another value by default to avoid the instant crash.

**Comment by jaebirds** [comment]
Agreed. I had this fixed in the latest commit so it should no longer happen.
