### ISSUE TITLE
Animate In and out

### ISSUE THREAD

**Issue by pickeditmate** [jaebirds/Alpha-Rotating-Feed-w-Goal#2]
Hi and firstly, thank you for the free code!

Hopefully I'm just too noob to figure it out but I can't seem to get the text to slide in upwards and then slide away down, it seems whatever I choose it just appears on screen instead.

Is this normal behaviour or am i missing something?

Thanks again

Dan

**Comment by jaebirds** [comment]
Hi Dan,

No problem! The animation settings can be found under "Settings" instead of "Animation settings". It can be found near the bottom and looks like this:

![1](https://user-images.githubusercontent.com/25286658/112763747-c3c0dc80-8fd3-11eb-9972-938aa967ca1a.png)

Confusing, I know, but I believe that "Animation settings" is for alerts only.

**Comment by pickeditmate** [comment]
Thanks Jane but I have that set in settings already, is it working for you within streamelements and can you maybe confirm your settings? I'll post my exact settings/timings in the morning as it's 3am.

**Comment by jaebirds** [comment]
I'm sorry, it looks like I misread your first comment and completely glossed over the slide part. What you're probably looking for is "fadeInUp" and "fadeOutDown". Those work well on my side.

**Comment by pickeditmate** [comment]
I must be missing something then, I'm in google chrome browser, followed steps 1-4 to create a blank widget custom css, removed what was there and copied in your code. 

No animations are working whatsoever, I've updated java to the latest version and I'm just updating windows updates just in case there's something else going on. 

Thanks for the help, I'm sure it's something blocking animations on my browser side for whatever reason

**Comment by pickeditmate** [comment]
I've checked and it is working just fine on my mobile phone browser, anyone got any idea why it's not working in windows 10 chrome? I've ran all available windows updates, got the latest java, checked that chrome is at latest version, checked javascript is enabled in it's settings. I just don't know where to check now

**Comment by jaebirds** [comment]
I'm not sure why it wouldn't be working in Chrome. It could very well be a Stream Elements issue too, but I don't know. One thing you could try is [clearing the cache](https://clear-my-cache.com/en/windows/google-chrome.html). Just as long as it works as a browser source in your stream, then it should be fine though.

**Comment by pickeditmate** [comment]
Thanks, it has to be something 9n my side, it must be something global as it doesn't work on stream either and I know from way back in my computer support days that IE is/was the global settings so it must be something with Edge.

I'll close this for now and if I ever figure out how to get back to that setting in win10 I'll add it to here for anyone else who has this problem. 

Cheers for your help and confirming animations are as they should be.
