### ISSUE TITLE
Icon Do Not Work

### ISSUE THREAD

**Issue by NMGStorm** [jaebirds/Alpha-Rotating-Feed-w-Goal#3]
![image](https://github.com/user-attachments/assets/b3b7fa02-e2a1-4ac0-b55a-6839fb784104)
They just show up as letters for some reason. can't get it to fix its self. i have tried reinstalling the overlay but that does not work.

Also does this work with kick? or can we get integration for kick ?

**Comment by jaebirds** [comment]
The original creators deleted the original icon file. I updated it with new icons.
